
import os, json, numpy as np
from PIL import Image, ImageStat

class DiseaseDetector:
    def __init__(self):
        base=os.path.dirname(os.path.dirname(__file__))
        self.model=None; self.labels=[]
        labels=os.path.join(base,"model","labels.json")
        if os.path.exists(labels):
            self.labels=json.load(open(labels,encoding="utf-8"))
        model=os.path.join(base,"model","disease_model.keras")
        if os.path.exists(model):
            try:
                from tensorflow.keras.models import load_model
                self.model=load_model(model)
            except Exception as e:
                print("Model load error:",e)

    def quality(self,path):
        im=Image.open(path).convert("RGB")
        w,h=im.size
        stat=ImageStat.Stat(im)
        brightness=sum(stat.mean)/3
        return {"width":w,"height":h,"brightness":round(brightness,1),
                "usable":w>=224 and h>=224 and 35<brightness<235}

    def predict(self,path,crop_hint="auto"):
        q=self.quality(path)
        if not q["usable"]:
            return {"crop":crop_hint.title() if crop_hint!="auto" else "Unknown",
                    "disease":"Image needs review","confidence":20.0,
                    "confidence_level":"low","quality":q,
                    "evidence":["Image quality gate rejected this photo as unreliable."],
                    "alternatives":[],"mode":"quality-gate","explainability":None}
        if self.model is None:
            return {"crop":"Tomato" if crop_hint=="auto" else crop_hint.title(),
                    "disease":"Model not installed","confidence":0.0,
                    "confidence_level":"low","quality":q,
                    "evidence":["No trained production model is installed."],
                    "alternatives":[],"mode":"model-missing","explainability":None}

        im=Image.open(path).convert("RGB").resize((224,224))
        x=np.asarray(im,dtype=np.float32)/255.0
        p=self.model.predict(np.expand_dims(x,0),verbose=0)[0]
        order=np.argsort(p)[::-1][:3]
        i=int(order[0]); conf=float(p[i])*100
        label=self.labels[i] if i<len(self.labels) else "Unknown"
        parts=label.split("___",1)
        crop=parts[0] if len(parts)==2 else crop_hint
        disease=parts[1] if len(parts)==2 else label
        return {"crop":crop.replace("_"," ").title(),"disease":disease.replace("_"," ").title(),
                "confidence":round(conf,1),
                "confidence_level":"high" if conf>=80 else "medium" if conf>=50 else "low",
                "quality":q,
                "evidence":["Prediction generated by the trained image classifier.",
                            "Top-3 probabilities are retained for uncertainty handling."],
                "alternatives":[{"disease":self.labels[int(j)].replace("___"," — ").replace("_"," "),
                                "confidence":round(float(p[j])*100,1)} for j in order[1:]],
                "mode":"live-model",
                "explainability":{"method":"Grad-CAM-ready",
                                  "note":"Enable /api/explain once the model's last convolution layer is configured."}}
